config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include Pagy::Backend
  before_action :set_tweet, only: %i[ show edit update destroy ]


  # GET /tweets or /tweets.json
  def index
    # Ordenar por la fecha de creación en orden descendente
    # @pagy, @tweets = pagy(Tweet.all, items: 10) # Paginar con 10 tweets por página
    # @tweets = Tweet.order(created_at: :desc)
    @pagy, @tweets = pagy(Tweet.order(created_at: :desc), items: 10)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_path, status: :see_other, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:userName, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend# Incluir el módulo Pagy Backend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Twitter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="row bg-black text-white">
      <section class="col-4 text-end">
        <%= image_tag "tw.jpg", alt: "Logo de la Aplicación" , class: "logo" %>
      </section>
      <section class="col-4">
        <%= yield %>
      </section>
      <section class="col-4">
      </section>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>@<%= tweet.userName %></strong>
  </p>
  <p>
    <%= tweet.description %>
  </p>
</div>

app/views/tweets/edit.html.erb
<% content_for :title, "Editing tweet" %>

<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New tweet", new_tweet_path %>
<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= link_to tweet_path(tweet), class: "tweet-link" do %>
      <div class="tweet ms-5">
        <%= render tweet %>
      </div>
    <% end %>
    <hr> <!-- Línea horizontal entre tweets -->
  <% end %>
  <%=raw pagy_nav(@pagy)%>
</div>

app/views/tweets/new.html.erb
<% content_for :title, "New tweet" %>

<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>